name: jethub-init-@BOARD@
arch: all
platform: linux
version: ${VERSION}
maintainer: JetHome <noreply@jethome.com>
section: utils
priority: optional
provides:
  - jethub-init
conflicts:
  - jethub-init
replaces:
  - jethub-init
  - armbian-bsp-cli-jethub@BOARD@
  - armbian-bsp-cli-jethub@BOARD@-current
  - armbian-bsp-cli-jethub@BOARD@-edge
  - armbian-bsp-cli-jethub@BOARD@-bleedingedge
  - armbian-bsp-cli-jethub@BOARD@-vendor
description: |
  JetHub @BOARD@ hardware init (GPIO lines, LEDs, radio modules) for Armbian.
  jethub-init entrypoint plus the @BOARD@ libjethubconfig.sh.
depends:
  - gpiod (>= 2)
contents:
  - src: armbian/jethub-init
    dst: /usr/lib/armbian/jethub-init
    file_info:
      mode: 0755
  - src: armbian/@BOARD@/libjethubconfig.sh
    dst: /usr/lib/armbian/libjethubconfig.sh
    file_info:
      mode: 0644
  - src: armbian/jethub-initer.service
    dst: /lib/systemd/system/jethub-initer.service
    file_info:
      mode: 0644
  - src: ../jethub-initer.service
    dst: /lib/systemd/system/basic.target.wants/jethub-initer.service
    type: symlink
